services:
  mongodb:
    container_name: mongo-db
    image: mongo:latest
    restart: unless-stopped
    ports:
     - "27017:27017"
    volumes: 
     - deceitcode-data:/data/db
  
volumes:
  deceitcode-data: