services:
  mongodb:
    container_name: mongo-db
    image: mongo:latest
    restart: unless-stopped
    ports:
     - "27017:27017"
    environment: 
     MONGO_INITDB_ROOT_USERNAME: test
     MONGO_INITDB_ROOT_PASSWORD: test