name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        
    - run: npm ci
    - run: npm run build --if-present
  
  docker:
    needs: ["build"]
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./server
        push: true
        tags: |
          joshl1215/deceitcode-backend:latest
          joshl1215/deceitcode-backend:${{ github.sha }}
    

